# Generated by Django 5.1.2 on 2025-04-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='balance_type',
            field=models.CharField(choices=[('affiliate', 'Affiliate Balance'), ('task', 'Task Balance')], default='affiliate', max_length=20),
        ),
    ]
